#!/bin/sh

	target="$1"
	sub='U32'
	sub2='GAMESTORAGE'
rming() {
	if [[ $target == *"$sub"* ]] ;
	then
		echo "Don't do it again, you moron!"
	elif
		[[ $target == *"$sub2"* ]]
	then
		echo "Don't do it! Those are your games!"
	else
		rm -rf $target
		echo "Deleting $target"
	fi
}
rming
