#!/bin/env sh

clip=$(xclip -selection c -o)
echo $clip
if [[ $1 == *"http"* ]]; then
  url=$1
elif [[ $clip == *"http"* ]]; then
  url=$clip
else
  read -p "Please enter the URL to view." url
fi

case "$(printf "mpv\\nyt-download\\nwget\\ncurl" | dmenu -fn "MeslosLGS NF"-i -p "Open link with:")" in
	"mpv") mpv --ao=pulse --no-config --script-opts=ytdl_hook-ytdl_path=yt-dlp --msg-level=all=no,ytdl_hook=trace --fs=yes $url >/dev/null 2>&1 &;;
	"yt-download") cd ~/Videos && yt-dlp --format "bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best" --merge-output-format mp4 $url ; exa -1 | grep -v OLD | grep -v NEW| tee OLD && exa -1 ~/Music/Videos |grep -v OLD | grep -v NEW| sed 's/(.*)//g' | sed 's/\[.*\]//g' | awk -F'-' '{ print $1 $2 ".mp4"}' | sed 's/\ *\./\./g'| sed 's/  / /g' | sed 's/://g' |sed 's/?//g' | sed 's/\.mp4\.mp4/\.mp4/g'|tee NEW ; ~/.scripts/rename ; ~/.scripts/mp3convert ; rm ~/Music/Vidoes/OLD ~/Music/Videos/NEW ;;
	"wget") wget $url;;
	"curl") curl $url;;
esac

clear
exit
