#!/usr/bin/env bash
## Get Volume
output_dev=$(wpctl status |grep Sinks -A 3 |grep "\*" |awk '{print $3 }' |sed 's/\.//g')
input_dev=$(wpctl status |grep Audio -A 10|grep Sources -A 6 |grep "\*" |awk '{print $3 }' |sed 's/\.//g')
# echo $output_dev $input_dev
get_vol() {
	while true; do
  	wpctl get-volume $output_dev | grep '^Volume:' | grep -oE '[0-9]{2}' 
	sleep 1
	done
}

## Set Volume
set_vol() {
  wpctl set-volume $output_dev $1"%"
}

## Toggle Volume
toggle_vol() {
  wpctl set-mute $output_dev toggle
}

## Get Volume Icon
#TODO: different icons according to volume level, maybe
get_volicon() {
	while true; do
  	MUTE="$(wpctl status |grep $output_dev |grep -o 'MUTED')"
  	if [[ "$MUTE" == "MUTED" ]]; then
    	echo "婢"
  	else
	  	echo "墳"
  	fi
		sleep 1
	done
}

## Get Mic Icon
get_micicon() {
	while true; do
  	MUTE="$(wpctl status |grep "\*"|grep $input_dev |grep -o 'MUTED')"
    # echo $MUTE
  	if [[ "${MUTE}" == "MUTED" ]]; then
    	echo ""
  	else
	 		echo ""
  	fi
		sleep 2
	done
}

## Toggle Mic
toggle_mic() {
  wpctl set-mute $input_dev toggle
}

## Get Mic
get_mic() {
	while true; do
  	wpctl get-volume $input_dev | grep '^Volume:' | grep -oE '[0-9]{2}' 
		sleep 1
	done
}

## Set Mic
set_mic() {
  wpctl set-volume $input_dev $1"%"
}




if [[ "$1" == "--set-vol" ]]; then
	set_vol "$2"
elif [[ "$1" == "--get-vol" ]]; then
	get_vol
elif [[ "$1" == "--toggle-vol" ]]; then
	toggle_vol
elif [[ "$1" == "--get-volicon" ]]; then
	get_volicon
elif [[ "$1" == "--get-micicon" ]]; then
	get_micicon
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-mic" ]]; then
	get_mic
elif [[ "$1" == "--set-mic" ]]; then
	set_mic "$2"
fi
